### ISSUE TITLE
[BUG] Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by Roxxik** [atom-extensions/dec-hex-oct-bin#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.1-2ff8f90
**System**: linux 4.0.7-2-ARCH
**Thrown From**: [dec-hex-oct-bin](https://github.com/erkkikeranen/dec-hex-oct-bin) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /home/phate/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/phate/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:4:199)
  at /home/phate/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:6:3
  at Object.<anonymous> (/home/phate/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:171:5)
  at Object.<anonymous> (/home/phate/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/local/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/phate/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin.coffee:1:20)
  at Object.<anonymous> (/home/phate/.atom/packages/dec-hex-oct-bin/lib/dec-hex-oct-bin.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/local/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/local/share/atom/resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/usr/local/share/atom/resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/usr/local/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/usr/local/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /usr/local/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /usr/local/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/usr/local/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/usr/local/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/local/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /usr/local/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/usr/local/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/usr/local/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/local/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/local/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -0:19.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:16.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "svn"
    ],
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
hex, v0.6.2
language-rust, v0.4.3
linter-clang, v2.26.0
linter-javac, v0.1.4
linter-rust, v0.1.0
racer, v0.15.2
rust-api-docs-helper, v0.5.1

# Dev
No dev packages
```

**Comment by vivi90** [comment]
Will be fixed by https://github.com/atom-extensions/dec-hex-oct-bin/issues/6.
